//my secript by MR DEATH LUMINOUS  LUMINOUS v1
//not sale this script

require("./database/module")

//GLOBAL PAYMENT
global.storename = "ཀ͜͡B̈ÜG̈_̈LUMINOUS V̈1👾༑"
global.dana = "243890432038"
global.qris = "https://i.postimg.cc/VsWWH3gY/DEATH MD-BUG-LUMINOUS-V1.jpg"


// GLOBAL SETTING
global.owner = "243890432039"
global.namabot = "ཀ͜͡B̈ÜG̈_̈LUMINOUS V̈1👾༑"
global.nomorbot = "243890432039"
global.nameCreator = "💀Mr.Death Luminous 💀"
global.linkyt = "https://whatsapp.com/channel/0029VajjpHoGZNCsyVLRRk1f"
global.autoJoin = false
global.antilink = true
global.versisc = '30'

// DELAY JPM
global.delayjpm = 5500



//GLOBAL THUMB

global.codeInvite = "Zokou-MD-WHATSAPP-BOT;;;=>eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoicUw1RnQ5VGNvb1pwSXVQZWNBbGozdVhoL2ROaDBCN25SN2l4UHd1SS9Faz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiMXNOQlBVVzJBNVNFZ1NMUkFST3ZxNGtxMDlNdFk5VHNyd2NuM1ZrMHZpaz0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJFTkVlS3VJQmZVODdaa0QvMFVuOWZLZnpqMExsNmdTUFlUNjJTRDZCY253PSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiI2TmQ4bXV0dEhNSDNoRzFPNmR0VG5PSEdGSE9VYmNERGNwb1hOSE9KczI4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImVBcTQvK3M2dWNLamlaRjVmbXM4UTRhdVJxNXdteVpXV3poSCs1U0ZQbUU9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik84Ym9DenRXdzB0T0JicURNYWtEb2l0b1VrbmlEWFRTZjFhQTRkY3FDVFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0VZNjhCa2Y0dzRFaDVqYmxMOGdrenJlbFdvcCtBSmhMWkx0bHIyaTltMD0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiczRQMHE1bW5qMzRWQ1M5YlVWeXFDTmRVTGVLTHdrVHBCNUUrdkVYejZCYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImJnSVhtbHN4QUdGZjhWbDloQTU3OHdxem1iK1QrOEVNT0c0NCsyMVplWXpsc1plSm9aVG8wVGhQeGZTY0xCYVdHWFhWR2ViRWIwaWJlWjNIRHpBL0NRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTg0LCJhZHZTZWNyZXRLZXkiOiJBa2JncTNFbklxcU5IYUgwZm9GVnd6TkZCVkI0RE5qblJ1R1dDUGhITXJRPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6ZmFsc2UsImFjY291bnQiOnsiZGV0YWlscyI6IkNMNjV4bzBGRUl2bTM3c0dHQUVnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiJyZ3JtZXBodVUwUFVCeG95YTNKb3diODJZOHNvMk1aZHR0NjgwNlI0RjFJPSIsImFjY291bnRTaWduYXR1cmUiOiJjNHZNakwzNTJINWw5QjJiaGxoV2dFekh2QjNEa2lxM2MrTm5KeXhzQi9ubVRWYVFNMjRWa09DU0ZHWHhBdXZKSi85aUN3R3JDNGpKTGt0VlB0V3pEZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiY0FvcGdsMGQvY0t0d011SUNiYSs2a3JkS0p0eWYvRStZaVZOSmliYmdEdWFQemlVWGRjQkRrbFR4VXJkdXFlNVl1dzJzTGpBUVFBd0o1RUt6MkVtRFE9PSJ9LCJtZSI6eyJpZCI6IjIyMzkwNzY1OTMxOjE5QHMud2hhdHNhcHAubmV0IiwibGlkIjoiMTk5NDMyODEzNDQ1MTg0OjE5QGxpZCJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiIyMjM5MDc2NTkzMToxOUBzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJhNEs1bnFZYmxORDFBY2FNbXR5YU1HL05tUExLTmpHWGJiZXZOT2tlQmRTIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQklJQlE9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3MzU5MTQyNTQsImxhc3RQcm9wSGFzaCI6IjN4WFdZWiJ9"
global.imageurl = 'https://i.postimg.cc/VsWWH3gY/DEATH MD-BUG-LUMINOUS-V1.jpg'
global.isLink = "https://whatsapp.com/channel/0029VajjpHoGZNCsyVLRRk1f"
global.packname = "ཀ͜͡B̈ÜG̈_̈LUMINOUS V̈1👾༑"
global.author = "💀Mr.Death Luminous 💀"
global.jumlah = "5"


let file = require.resolve(__filename)
fs.watchFile(file, () => {
	fs.unwatchFile(file)
	console.log(chalk.redBright(`Update ${__filename}`))
	delete require.cache[file]
	require(file)
})
